FROM dakshinatharindu/debian:latest

RUN mkdir -p /opt/riscv

RUN wget https://github.com/dakshinatharindu/dockerfiles/releases/download/rv32g/riscv.tar.gz
RUN tar -xvf riscv.tar.gz -C /opt

ENV PATH="/opt/riscv/bin:${PATH}"

RUN rm -rf riscv.tar.gz