FROM eclipse-temurin:24-jre-noble

ENV SBT_VERSION=1.10.11
RUN apt-get update && apt-get install -y curl unzip && \
    curl -L -o sbt-$SBT_VERSION.zip https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.zip && \
    unzip sbt-$SBT_VERSION.zip -d ops

ENV PATH="/ops/sbt/bin/:${PATH}"