FROM eclipse-temurin:24-jre-noble

ENV SBT_VERSION=1.10.11
RUN apt-get update && apt-get install -y sudo curl unzip build-essential && \
    curl -L -o sbt-$SBT_VERSION.zip https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.zip && \
    unzip sbt-$SBT_VERSION.zip -d /opt

ENV PATH="/opt/sbt/bin/:${PATH}"

# Install Verilator
RUN apt-get install -y git help2man perl python3 make libfl2 libfl-dev zlib1g zlib1g-dev ccache \
    mold libgoogle-perftools-dev numactl perl-doc git autoconf flex bison

RUN git clone https://github.com/verilator/verilator
RUN cd verilator && \
    git checkout stable && \
    autoconf && \
    ./configure --prefix=/opt/verilator && \
    make -j$(nproc) && \
    make install
# Set environment variables for Verilator
ENV PATH="/opt/verilator/bin:${PATH}"

# Create a user named chisel and give sudo access
RUN useradd -m -s /bin/bash chisel && \
    echo "chisel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
# Switch to the new user
USER chisel
WORKDIR /home/chisel

