FROM dakshinatharindu/debian:latest

# Install Python 3 and pip as root
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv

# create a user named angr and give sudo access
RUN useradd -m -s /bin/bash angr && \
    echo "angr ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Switch to the new user
USER angr
WORKDIR /home/angr

# Install angr using venv
RUN python3 -m venv angr-venv && \
    . angr-venv/bin/activate && \
    pip install --upgrade pip && \
    pip install angr

