# Use the official Debian image
FROM debian:latest

# Update the package list and install necessary packages
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends bash curl wget vim \
    build-essential autoconf git wget python3 python3-pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*